services:
  yandex-music-bot:
    image: yandex-music-download-tgbot:v1.0.1
    container_name: yandex-music-download-tgbot
    restart: unless-stopped
    volumes:
      - downloads:/app/downloads
    user: "${UID}:${GID}"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - YANDEX_MUSIC_TOKEN=${YANDEX_MUSIC_TOKEN}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}

volumes:
  downloads:
