version: '3.8'

services:
  yandex-music-bot:
    build: .
    container_name: yandex-music-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - YANDEX_MUSIC_TOKEN=${YANDEX_MUSIC_TOKEN}
    volumes:
      - downloads:/app/downloads
      - temp:/app/temp

volumes:
  downloads:
  temp: