services:
  yandex-music-bot:
    image: yandex-music-download-tgbot:v1.0.0
    container_name: yandex-music-download-tgbot
    restart: unless-stopped
    volumes:
      - downloads:/app/downloads

volumes:
  downloads: